[2024-07-19T19:33:01.484+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: computer_data.insert_memory_data_task scheduled__2024-07-19T19:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
