[2024-07-17T13:50:09.567+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: computer_data.insert_battery_data_task scheduled__2024-07-17T13:42:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
