[2024-07-17T10:37:39.732+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: computer_data.insert_memory_data_task manual__2024-07-17T10:37:27.571606+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
