[2024-07-16T10:17:36.406+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: computer_data.insert_cpu_data_task scheduled__2024-07-16T10:15:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
